[package]
name = "server_core"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
axum = "0.4"
tracing = "0.1"
tokio = { version = "1.17", features = ["full"] }
