[package]
name = "server_core"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
axum = "0.5"
tracing = "0.1"
server_oauth = { path = "../server_oauth" }
server_config = { path = "../server_config" }